name: Build Tree-sitter grammar
on:
  workflow_call:
    inputs:
      grammar-name:
        description: Grammar name to use in the package names
        required: true
        type: string
      cli-version:
        description: Tree-sitter CLI version
        required: false
        type: string
        default: "0.27.0"
permissions:
  contents: write
jobs:
  build:
    name: ${{ inputs.grammar-name }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-amd64
            runner: ubuntu-24.04
            extension: so
          - target: linux-arm64
            runner: ubuntu-24.04-arm
            extension: so
          - target: macos-arm64
            runner: macos-14
            extension: dylib
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tree-sitter CLI
        run: cargo install tree-sitter-cli --version "${{ inputs.cli-version }}"
      - name: Build and package
        uses: julianolf/tree-sitter-builder@main
        with:
          grammar-name: ${{ inputs.grammar-name }}
          extension: ${{ matrix.extension }}
          target: ${{ matrix.target }}
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.grammar-name}}-${{ matrix.target }}
          path: ${{ inputs.grammar-name}}-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.grammar-name }}-*
          path: dist
          merge-multiple: true
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
          GRAMMAR_NAME: ${{ inputs.grammar-name }}
        run: gh release create "$TAG" --title "$TAG" --generate-notes "dist/$GRAMMAR_NAME-*.tar.gz"
